---
title: "Microbiome analysis - Mirzapur follow-up"
author: "Maureen A. Carey"
date: "09/01/2020"
output: html_document
---

# Load packages and data

```{r setup, include=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/local_documents/work/crypto_microbiome/cryptosporidium_microbiome/")

# load packages
library(ggplot2); library(phyloseq); library(dplyr)

# load data
load("/Users/maureencarey/local_documents/work/crypto_microbiome/cryptosporidium_microbiome/results/P5output_plot_2020_09_11.RData")

# set constants
SEED_INT = 10; set.seed(SEED_INT); options(scipen=10000); theme_set(theme_bw())
colors = c("#1F78B4","#FF7F00","#666666", 'light gray')
names(colors) = c('diarrheal','subclinical','no crypto','both')
# blue = "#1F78B4" orange = "#FF7F00" gray = "#666666"

write.csv(sample_data(ps_mirzapur_rare)[,c(1,2)], "/Users/maureencarey/local_documents/work/crypto_microbiome/manuscript_drafts/info_for_dbGaP/mirzapur_samples_passedQC.csv", row.names = F)

```

# Plot - Fig 4F

```{r}

ggplot(df, aes(x = Site, y = value, color = Site)) + 
  geom_boxplot(outlier.shape = NA) + 
  geom_point(alpha = 0.5, position = position_jitter(width = 0.3, height = 0, seed = SEED_INT)) + 
  facet_wrap(~time) +
  scale_y_sqrt() +
  scale_color_manual(values = c('black','darkgray'), guide = F) +
  geom_hline(yintercept = 0.2, linetype = 'dotted', alpha = .75) +
  ylab('relative abundance')
ggsave("/Users/maureencarey/local_documents/work/crypto_microbiome/cryptosporidium_microbiome/figures/Fig4F_mega_box_Mirzapur.png",
       width = 3.2,height = 3.5,units = "in",dpi = 300)

```

## Table 1-like data for methods

```{r}

length(unique(sample_data(ps_mirzapur_rare)$Child.ID))
length((sample_data(ps_mirzapur_rare)$Child.ID))
table(sample_data(ps_mirzapur_rare)$Clinical.type)
min(sample_data(ps_mirzapur_rare)$Date.of.collection)
max(sample_data(ps_mirzapur_rare)$Date.of.collection)

```


Species
```{r}

load("/Users/maureencarey/local_documents/work/crypto_microbiome/data_cannot_be_shared/data.RData")
crypto_cts = burden_all_path %>% filter(crypto == 1) %>%
  mutate(date_of_collection = as.Date(gsub('.{8}$', '', as.character(DOC)), "%m/%d/%Y")) %>%
  select(CHILDID, date_of_collection, CRYCTRT, type) %>% filter(CHILDID %in% burden_mirpur$SID)
rm(list= ls()[! (ls() %in% c('ps_mirzapur_rare','crypto_cts'))])

tempsampledata = sample_data(ps_mirzapur_rare)
tempsampledata = merge(tempsampledata, crypto_cts %>% select(-type), by.x = c("Child.ID","Date.of.collection"), by.y = c("CHILDID","date_of_collection"), all.x = T)
tempsampledata[tempsampledata$Clinical.type %in% c(1,2),"CRYCTRT"] = 45 # if predetection, Crypto DNA was not assessed or detected

# get other Ct values (targeted qPCRs)
all_ct = read.table("~/local_documents/work/crypto_microbiome/data_cannot_be_shared/Cq_values_all.txt",header=TRUE, sep='\t',comment.char = "",stringsAsFactors = F, na.strings = c("#N/A"))
all_ct[is.na(all_ct)] = 45 # replace #NA and real NAs with 0
all_ct[all_ct == 0] = 45 # replace #NA and real NAs with 0
tempsampledata = tempsampledata %>% mutate(sample_id_mod = substr(sample.id,1,nchar(sample.id)-5))
tempsampledata = merge(tempsampledata, all_ct, by.x = "sample_id_mod", by.y = "sample.id", all.x = T)
rownames(tempsampledata) = tempsampledata$use_as_rows; tempsampledata$use_as_rows = NULL

#12=diarrhea; 10=Clinic Visit; 1 =pre-clinic visit positive; 2=pre-diarrhea case positive

#all
ifelse(tempsampledata %>% filter(Clinical.type %in% c(10,12)) %>% select(LIB13.C..hominis)<40,1,0) %>% table()
ifelse(tempsampledata %>% filter(Clinical.type %in% c(10,12)) %>% select(C..mel.y)<40,1,0) %>% table()
ifelse(tempsampledata %>% filter(Clinical.type %in% c(10,12)) %>% select(Pan_crypto)<40,1,0) %>% table()

# diarrheal
ifelse(tempsampledata %>% filter(Clinical.type %in% c(12)) %>% select(LIB13.C..hominis)<40,1,0) %>% table()
ifelse(tempsampledata %>% filter(Clinical.type %in% c(12)) %>% select(C..mel.y)<40,1,0) %>% table()
ifelse(tempsampledata %>% filter(Clinical.type %in% c(12)) %>% select(Pan_crypto)<40,1,0) %>% table()


# subclin
ifelse(tempsampledata %>% filter(Clinical.type %in% c(10)) %>% select(LIB13.C..hominis)<40,1,0) %>% table()
ifelse(tempsampledata %>% filter(Clinical.type %in% c(10)) %>% select(C..mel.y)<40,1,0) %>% table()
ifelse(tempsampledata %>% filter(Clinical.type %in% c(10)) %>% select(Pan_crypto)<40,1,0) %>% table()


ntaxa(subset_taxa(ps_mirzapur_rare, Genus == "Megasphaera"))

```
